//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TurfirmaApp.DataFilesApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clients
    {
        public int Id { get; set; }
        public string FullName { get; set; }
        public int GenderId { get; set; }
        public int Age { get; set; }
        public string Childrens { get; set; }
        public Nullable<int> HotelId { get; set; }
        public Nullable<int> TourId { get; set; }
    
        public virtual Genders Genders { get; set; }
        public virtual Hotels Hotels { get; set; }
        public virtual Tours Tours { get; set; }
    }
}
